[pytest]
# Marcadores personalizados para filtrar la ejecucion de pruebas (-m)
markers =
    login: Pruebas del modulo de ingreso
    inventory: Pruebas del catalogo de inventario
    cart: Pruebas del carrito de compras

# Reconocimiento automatico de archivos y funciones de prueba
python_files = test_*.py
python_functions = test_*

# Opciones por defecto para la ejecucion
# -v: modo detallado (verbose)
# -s: muestra en consola las salidas/mensajes impresos (print) sin capturarlos ni ocultarlos
# --html=report/reporte.html: genera el reporte HTML en la carpeta 'report'
# --self-contained-html: integra los estilos CSS directamente dentro del archivo HTML

addopts = -v -s --html=report/reporte.html --self-contained-html